version: "3"
services:
  todo-front:
    container_name: todo-front
    build:
      context: .
      dockerfile: ./todo-front/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./todo-front:/todo-front
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app_network

  todo-server:
    container_name: todo-server
    build:
      context: ./todo-server/
    ports:
      - 3001:3001
    volumes:
      - .:/todo-front
    tty: true
    stdin_open: true
    expose:
      - 4000
    networks:
      - app_network
    depends_on:
      - mysql
    environment:
      dataSourceClassName: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      dataSource.user: root
      dataSource.password: ${MYSQL_ROOT_PASSWORD}
      dataSource.databaseName: ${MYSQL_DATABASE}
      dataSource.setDriverClassName: com.mysql.cj.jdbc.Driver

  mysql:
    build: ./mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      # - DB_PORT=3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app_network

  # keycloak:
  #   build: ./keycloak
  #   platform: linux/amd64
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mysql
  #   networks:
  #     - app_network
  #   volumes:
  #     - .:/keycloak

  #   container_name: keycloak
  #   tty: true
  #   stdin_open: true
  #   # Hot Module Replacement (HMR) is enable for virtual box.
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true



networks:
  app_network:

